url: https://benpolasek.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Ben Polasek
email: benpolasek@hotmail.com
description: "Portfolio of Current and Past Projects"


# Team names, titles and social links
people:
- name: Ben Polasek
  pic: 1
  position: Data Science | Mathematician | Musician
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/benpolasek

# Postal address (add as many lines as necessary)
address:
  - line: Toronto, Ontario, Canada

# Build settings
markdown: kramdown
permalink: pretty
